FROM node:8.15

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install

COPY . .

# COPY cloud-build/demo/entrypoint.sh .

EXPOSE 80
CMD [ "npm", "run", "start" ]
